global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prometheus-grafana-exporter'

scrape_configs:
  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: prometheus
    static_configs:
      - targets: ['golang:9000']
  - job_name: golang
    metrics_path: /metrics
    static_configs:
      - targets:
          - golang:9000
